language: julia
julia:
  - nightly
  - 1.1
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# after_success:
#   - julia -e 'using Pkg; cd(Pkg.dir("GeoWKB")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
 
codecov: true
# coveralls: true
